spring:
  datasource:
    url: jdbc:mysql://localhost:8889/office_management
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    #    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    #    pool:
    #      max-active: 5
    #      max-wait: -1
    #      max-idle: 8
    #      min-idle: 0
    timeout: 3000
